# -*- coding: utf-8 -*-
"""testfile.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kIsz8-oGbahwCh2yhzg1KxvaTTjH3tpv
"""

def exchange_values():
    x = 100
    y = 12
    print("Before exchange: x=", x, " y=", y)
    x, y = y, x
    print("After exchange: x=", x, " y=", y)
    return x, y

if __name__ == '__main__':
    exchange_values()
    print("process is done")
else:
    print('not executed')
